---
title: "Profskills"
---

I am a postgraduate student in the University of Glasgow's
[Institute of Neuroscience and Psychology](http://www.gla.ac.uk/researchinstitutes/neurosciencepsychology/).
I work with [Dr Maria Gardani](https://www.gla.ac.uk/schools/psychology/staff/mariagardani/)

I graduated from the University of Glasgow MA Psychology with first class honours. I am currently completing an Msc Research Methods of Psychological Science within the Sleep and Circadian Rrhythm Research Group at the University of Glasgow. 

#My research interests:

My current research interests focus on sleep disturbances ad insomnia after brain injury and care-giver sleep quality.  I am also specfically  interested in experiences of sleep post-stroke and treatment preferences and perspectives. 

My  other research interests relate to the relationship between experiences of fatigue and mental health. 



#Research Experience

My undergraduate research project investigated the association between fatigue, mental health and sleep disturbances in 237 carers for those with brain injury. Our study found that carers had poor sleep quality, significant levels of physical and mental fatigue and poor psychological wellbeing. We also found that depression and fatigue severity predicted poor sleep quality. These results provide insight into an under researched area and emphasise the necessity for carer centred interventions and support provisions which aim to improve sleep hygiene practices, address psychology wellbeing and fatigue symptomology. 




  
        

         
  